### ISSUE TITLE
Custom DropdownItem?

### ISSUE THREAD

**Issue by Jalalx** [n4kz/react-native-material-dropdown#118]
Hello

I'm trying to create custom items like multi-line text with different font name or font size for each section and maybe an icon inside each item.

What should I modify to achieve this? I see in `renderItem` method, you create a `DropdownItem` and simply returning it:
https://github.com/n4kz/react-native-material-dropdown/blob/4526671144e4c7296588872819e2b6b261bd6c85/src/components/dropdown/index.js#L564-L638

I couldn't find any property for rendering custom items. Is there any extensibility point for this?
Thank you.

**Comment by jhanstra** [comment]
I think I'm trying to do something similar to you @Jalalx https://github.com/n4kz/react-native-material-dropdown/issues/119
