### ISSUE TITLE
Dropdown appears overtop of status bar

### ISSUE THREAD

**Issue by brianmclachlin** [n4kz/react-native-material-dropdown#12]
When I have the last option selected in the dropdown and then open the dropdown the options get cut off by the top of the app.

iOS Simulator
![screen shot 2017-08-18 at 11 39 25 am](https://user-images.githubusercontent.com/13853211/29466278-51e93be4-840a-11e7-9fee-43ea846c7248.png)

Android
![screenshot_20170818-115050](https://user-images.githubusercontent.com/13853211/29466647-a9e90864-840b-11e7-8a93-87d84d8f2ecb.png)

Any way to make it so that the dropdown goes down if there is not enough room at the top of the app?

**Comment by n4kz** [comment]
Thanks for reporting, I'm planning to fix this in next release.

**Comment by n4kz** [comment]
Fixed by adding `dropdownPosition` prop in #14. Released in `0.4.0`.
