### ISSUE TITLE
Disable dynamic position option?

### ISSUE THREAD

**Issue by reilem** [n4kz/react-native-material-dropdown#14]
Thank you so much for making this library, the material design fits really well into android apps. However I feel like the dynamic positioning is rather irritating. I feel like a user would expect a dropdown to appear at the same position every time. An option to turn this off would be splendid. The dynamic positioning also sometimes causes the drop down list to go underneath the status bar.

Sorry if this option is already present but I couldn't find anything about it in the docs. Alternatively if you can find a way to just prevent the dropdown from going under the status bar that would great as well.

**Comment by n4kz** [comment]
Thanks for issue! Added new prop `dropdownPosition` with optional numeric value. Positive and zero values fix dropdown position on Nth item counting from top and negative values do the same from bottom. 

Released in `0.4.0`.
