### ISSUE TITLE
How to change Dropdown label's weight to bold ?

### ISSUE THREAD

**Issue by PrinceSharzeel** [n4kz/react-native-material-dropdown#144]

**Comment by Ahmed-Imam** [comment]
any luck ?

**Comment by PrinceSharzeel** [comment]
No, did it by adding 

```
 <View style={[styles.single]}>
     
     <Text style={ {fontWeight:'bold',marginTop:10,fontSize:RF(2),backgroundColor:'white',color:'#006DB7'
      }    }>LABEL</Text>  
      
                <Dropdown
                style={{ width:40 }}
               dropdownOffset={{top:2,left:0}}
                fontSize={RF(2)}
                value="Select"
                onBlur={this.checkNet.bind(this)}
                textColor='#006DB7'
                baseColor='#006DB7'
                data={this.state.datalist}
            />
     </View>
```

**Comment by rdewolff** [comment]
Did you check https://github.com/n4kz/react-native-material-dropdown/issues/75 ?

**Comment by Oakyden** [comment]
use this prop like so...              labelTextStyle={{fontWeight: '800'}}

**Comment by ws7one** [comment]
> use this prop like so... labelTextStyle={{fontWeight: '800'}}

This doesnt work

**Comment by Oakyden** [comment]
Can you tell me which font you are using ? sometimes if you have an specifically defined font then weight won't work. For example if you use lato, then you need to change the font family property to 'lato-bold' or 'lato-black' when you want bold text.

Other than that i can only imagine its a different version to mine or similar as the above definitely worked for me.

**Comment by ghost** [comment]
> Can you tell me which font you are using ? sometimes if you have an specifically defined font then weight won't work. For example if you use lato, then you need to change the font family property to 'lato-bold' or 'lato-black' when you want bold text.
> 
> Other than that i can only imagine its a different version to mine or similar as the above definitely worked for me.

@Oakyden I just looked into the docs. Are you sure that  there is 'labelTextStyle' prop? I can't see it in the docs

Adding this prop to <Dropdown /> does not affects label

**Comment by Subway19** [comment]
> Can you tell me which font you are using ? sometimes if you have an specifically defined font then weight won't work. For example if you use lato, then you need to change the font family property to 'lato-bold' or 'lato-black' when you want bold text.
> 
> Other than that i can only imagine its a different version to mine or similar as the above definitely worked for me.

labelTextStyle prop only works for fontFamily, not working to change color of font, what's the issue?

**Comment by saurabh874** [comment]
labelTextStyle prop only works for fontFamily, not working to change color of font, what's the issue?
even i am using "basecolor" props so by default my arrow icon color is also changing in initial state
any solution for this?

**Comment by saurabh874** [comment]
Got the solution use placeholderTextColor props for label color and if you want to change color of arrow use basecolor props.
