### ISSUE TITLE
How to hide the triangle arrow from the dropdown

### ISSUE THREAD

**Issue by renishdeveloper** [n4kz/react-native-material-dropdown#145]
I want the drop down without the triangle arrow for dropdown.

**Comment by celineotter** [comment]
try: renderAccessory={() => null}

**Comment by renishdeveloper** [comment]
@celineotter Thank you so much, I got the drop down without the triangle arrow for dropdown but next, I want is when I select an item from the dropdown the label goes at the top of what I selected from the dropdown item.
Is there any property that satisfies want I want.
Thanks in advance.

**Comment by renishdeveloper** [comment]
It's done if I use **value** instead of **label** , is it generates any problem for me in future..???

**Comment by renishdeveloper** [comment]
I'm closing this issue as got the solution.
Feel free to open
