### ISSUE TITLE
Unnecessary label required

### ISSUE THREAD

**Issue by ercpereda** [n4kz/react-native-material-dropdown#16]
I'm getting this warning if not enter the label parameter, but the component works fine without it. I think it should be optional.

Btw, thanks for a great component it helps me a lot.

**Comment by n4kz** [comment]
Thanks for issue, label is required by underlying [`TextField`](https://github.com/n4kz/react-native-material-textfield) component, and can be set to empty string to omit warning.  I'm working on option to replace `TextField` with arbitrary components in #5.
