### ISSUE TITLE
Error in version 0.4.0

### ISSUE THREAD

**Issue by ercpereda** [n4kz/react-native-material-dropdown#17]
I just updated to v0.4.0 and every time I push the dropdown I get this error

![image](https://user-images.githubusercontent.com/13546685/30603975-9ac88074-9d3f-11e7-913f-6dde66bec52b.png)

**Comment by n4kz** [comment]
Thanks for reporting, looks like this method is available since RN 0.46.0. Fixed and released in `0.4.1`.
