### ISSUE TITLE
allowFontScaling={false} works not proper

### ISSUE THREAD

**Issue by VladimirZhmakov** [n4kz/react-native-material-dropdown#179]
When I put allowFontScaling={false} in Dropdown control , it looks okay, but this property is not propagated to dropdown items. 
Even if I try to scale font size internally and set it through 'itemTextStyle' object property, nothing happens. Probably because fontSize from 'itemTextStyle' is  overriden by fontSize from 'textStyle' 
here code snippet:
<Dropdown
                        label=''
                        animationDuration={0}
                        allowFontScaling={false}
                        itemCount={10}
                        fontSize={heightScale(16)}
                        labelFontSize={heightScale(12)}
                        itemPadding={heightScale(5)}
                        dropdownOffset={{ top: heightScale((Platform.OS !== 'android' ? 17 : 12)), left: 0 }}
                        containerStyle={{}}
                        itemTextStyle={{ fontsize: moderateScale(16), }}
                        inputContainerStyle={{ borderBottomColor: 'transparent' }}
                        onChangeText={(text) => this._onChangePhoneCode(text, onChangePhoneCode)}
                        value={phoneCode}
                        data={Constants.countryCodes}
                    />

is ther any way to :
propagade - allowFontScaling to dropdown items
or
allow to control fontSize of dropdown items via 'itemTextStyle' property ?

**Comment by kumarutsav111** [comment]
node-modules-> React-native-material-dropdown->src->components->dropdown->index.js add allowFontScaling= {false} , like <DropdownItem index={index} {...props}>
        <Text  allowFontScaling= {false} style={[styles.item, itemTextStyle, textStyle]} numberOfLines={1}>
          {title}
        </Text>
      </DropdownItem>

**Comment by VladimirZhmakov** [comment]
This helped, thanks a lot!
