### ISSUE TITLE
Change fontFamily of the items?

### ISSUE THREAD

**Issue by ercpereda** [n4kz/react-native-material-dropdown#18]
Is there a way to change the fontFamily of the items in the component?

**Comment by n4kz** [comment]
Yes, please take look at `itemTextStyle` prop.

**Comment by ercpereda** [comment]
Thanks for the response, but that only change the styles of the dropdown items. I need change the selected option too.

**Comment by n4kz** [comment]
Styles from `style` prop are passed directly to underlying `TextField`, so you can use something like `<Dropdown style={{ fontFamily: 'My Font' }} />` .
