### ISSUE TITLE
Change arrow icon

### ISSUE THREAD

**Issue by ercpereda** [n4kz/react-native-material-dropdown#19]
I don't know if this is wanted because the component supposed to follow the material guidelines. But I think that can be used the ability of change de arrow icon, and let the material looks by default.
If you decide going forward with this, I recommend specify any icon of https://github.com/oblador/react-native-vector-icons#android

**Comment by n4kz** [comment]
Thanks for question! Arrow icon can be changed using `renderAccessory` prop. I'm using `react-native-vector-icons` myself, but in my opinion direct dependency greatly increases component installation complexity, as font installation and project modification are required.

For usage example please take look at [`TextField` example project](https://github.com/n4kz/react-native-material-textfield/blob/master/example/app.js#L223).
