### ISSUE TITLE
Event is undefined on focus()

### ISSUE THREAD

**Issue by Tofugrass** [n4kz/react-native-material-dropdown#2]
In index.js, line ~119, event is undefined when the dropdown is opened via the focus() function. This is because onPress() is never called. We fixed the issue by wrapping
`event.nativeEvent.locationY -= 16;
 this.ripple.startRipple(event);`

with `if(event != undefined){`

**Comment by n4kz** [comment]
Thanks for reporting! Released in `0.0.8`.
