### ISSUE TITLE
Underline highlighting.

### ISSUE THREAD

**Issue by JSafaiyeh** [n4kz/react-native-material-dropdown#22]
I have a need to control the color of the highlighting. Customize to be different from the floating label.

Also, customize different colors when it is  active/inactive.

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Passing different set of options to underlying ripple effect for dropdown items is not possible right now and not planned in near future. However I can add option to completely override dropdown item rendering, how it's already done for base component.
