### ISSUE TITLE
Bottom Border

### ISSUE THREAD

**Issue by dwivediamit** [n4kz/react-native-material-dropdown#23]
How to remove Border-bottom from dropdown Please help...

**Comment by n4kz** [comment]
Thanks for question. Underline can be removed from `TextField` component starting from `0.10.0`, as described in n4kz/react-native-material-textfield#47. I've updated dependencies and just released `0.4.2`, so now it's possible to pass `inputContainerStyle={{ borderBottomColor: 'transparent' }}` to completely hide underline.

**Comment by dwivediamit** [comment]
Thanks for the solution.
So now again i have to run this command line 'npm install --save react-native-material-dropdown' for update

**Comment by dwivediamit** [comment]
**This is my Code**
<Dropdown
      label='Gender'
      data={data}
      labelFontSize={17}
      baseColor="#575757"
      textColor="#575757"
      itemColor="#000"
      selectedItemColor="#000"
/>

**Comment by dwivediamit** [comment]
#inputContainerStyle={{ borderBottomColor: 'transparent' }} it is not working for dropdwon

**Comment by dwivediamit** [comment]
Hi, is it possible to remove underline from react-native-material-dropdown i have tried this **inputContainerStyle={{ borderBottomColor: 'transparent' }**  but this is also not working please help if possible.

**Comment by dwivediamit** [comment]
Thanks i have fixed it inside `node_modules\react-native-material-textfield\src\components\field` then index.js find **inputContainerStyle** and put **borderBottomColor: 'transparent**'

**Comment by Nisharunnisaa** [comment]
Hii,
Is there any option to change the drop-down line width?

**Comment by joaosilvamaestro** [comment]
@Nisharunnisaa just use this: inputContainerStyle={{ borderBottomWidth: 2}}

		<Dropdown
				label={props.label}
				data={props.data}
				containerStyle={{
					marginTop: 10
				}}
				**inputContainerStyle={{ borderBottomWidth: 2}}**
				borderStyle={'dotted'}
				value={props.value}
				onChangeText={(valor) => this.handleChange(valor)}
				itemColor={'black'}
				textColor={'black'}
			/>

**Comment by cassioseffrin** [comment]
@Nisharunnisaa just use this: inputContainerStyle={{ borderBottomWidth: 2}}

	```
<Dropdown
			label={props.label}
			data={props.data}
			containerStyle={{
				marginTop: 10
			}}
			**inputContainerStyle={{ borderBottomWidth: 2}}**
			borderStyle={'dotted'}
			value={props.value}
			onChangeText={(valor) => this.handleChange(valor)}
			itemColor={'black'}
			textColor={'black'}
		/>
```

**Comment by cassioseffrin** [comment]
@Nisharunnisaa just use this: inputContainerStyle={{ borderBottomWidth: 2}}

```
<Dropdown
			label={props.label}
			data={props.data}
			containerStyle={{
				marginTop: 10
			}}
			**inputContainerStyle={{ borderBottomWidth: 2}}**
			borderStyle={'dotted'}
			value={props.value}
			onChangeText={(valor) => this.handleChange(valor)}
			itemColor={'black'}
			textColor={'black'}
/>
```

**Comment by cassioseffrin** [comment]
@Nisharunnisaa just use this: inputContainerStyle={{ borderBottomWidth: 2}}

```
 <Dropdown
	label={props.label}
	data={props.data}
	containerStyle={{
		marginTop: 10
	}}
	value={props.value}
	onChangeText={(valor) => this.handleChange(valor)}
	itemColor={'black'}
	textColor={'black'}
	inputContainerStyle={{ borderBottomWidth: 2 }}
/>
```
