### ISSUE TITLE
Make container outlined, remove line

### ISSUE THREAD

**Issue by dylangolow** [n4kz/react-native-material-dropdown#246]
* when adding border to container, it wraps the input with the error message if it exists, and the red line beneath input returns even if lineWidth={0}
* Looking to make this like the outlined variant of material design

Are there are easy fixes to this? 
![Screen Shot 2020-07-28 at 12 25 45 PM](https://user-images.githubusercontent.com/24441906/88693601-7bac8b80-d0cd-11ea-960d-febd7b1ef31c.png)

**Comment by dylangolow** [comment]
I solved this by setting:
* lineWidth={0}
* activeLineWidth={0}
* disabledLineWidth={0}
* removing error prop
* adding custom error under the input

The text and caret are still not perfectly aligned but it's pretty well formatted.

**Comment by dylangolow** [comment]
For anyone reading this. Remember you can pass the props expected for https://www.npmjs.com/package/react-native-material-textfield as this is used within this dropdown component.

**Comment by Harikasai999** [comment]
hi i am also facing this issue. Please give any suggestion for this...
