### ISSUE TITLE
pickerStyle seem to have no effect!

### ISSUE THREAD

**Issue by raihanrazi** [n4kz/react-native-material-dropdown#25]
Thanks for the great library. It's really easy to use. However, I am having trouble styling the actual dropdown component. I want to change it's background colour and add a top border. The prop that came to mind that could achieve this is pickerStyle. However, it doesn't seem to have any effect on the styling. Any help on this would be greatly appreciated. Cheers!

`<Dropdown
      textColor='#efe1db'
              baseColor="#efe1db"
              itemColor='#efe1db'
              selectedItemColor='#000'
              value={data[0].value}
              data={data}
              dropdownPosition={0}
              label=""
              labelHeight={10}
              // inputContainerStyle={
              //   {backgroundColor: "red"}
              // }
              pickerStyle={{
                width: 300,
                borderTopWidth: 2,
                borderTopColor: '#78818a',
                backgroundColor: '#3c3d3e',
              }}
            />`

**Comment by n4kz** [comment]
Thanks for question, please verify component version as `pickerStyle` is available since `0.5.0`.

**Comment by raihanrazi** [comment]
This worked for 0.5.0. Cheers.
