### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNative.Animated.Text.propTypes.style')

### ISSUE THREAD

**Issue by Victorvikson1996** [n4kz/react-native-material-dropdown#259]

**Comment by brunosantanarj** [comment]
Same issue, some update ?

**Comment by brunosantanarj** [comment]
Duplicate https://github.com/n4kz/react-native-material-dropdown/issues/249

**Comment by zapcriativo** [comment]
For those who don't want to edit node_modules each time, here is a patch file according to @Fabrice-Beya advice using patch-package.

Instruction:

Create **patches** directory in your project's root
Copy [patch](https://gist.github.com/zapcriativo/4abaf54a54b604e9a58fc507d38d9171) to patches/react-native-material-textfield+0.12.0patch
**yarn add patch-package postinstall-postinstall** or **npm i patch-package**
**yarn patch-package or npx patch-package**

Fix is already applied. Add the following to package.json to not repeat the same next time:

```
"scripts": {
  "postinstall": "patch-package"
 }
```

Fix using example from https://github.com/n4kz/react-native-material-textfield/issues/249#issuecomment-625791243 editing version version of patch only

**Comment by Victorvikson1996** [comment]
> Same issue, some update ?

**Comment by will-sklenars** [comment]
> patches/react-native-material-textfield+0.12.0patch

@zapcriativo, I believe you missed a `.`
Should be `patches/react-native-material-textfield+0.12.0.patch`
