### ISSUE TITLE
Failed prop type: Invalid prop `data[0].label`

### ISSUE THREAD

**Issue by Flavien** [n4kz/react-native-material-dropdown#26]
I am using the Dropdown with data such as:

```
const dropDownValues = [
    { value: "value1", label: "Label one" },
    { value: "value2", label: "Label two" },
];
```

The dropdown renders and functions fine, however I am getting a react-native warning:

Warning: Failed prop type: Invalid prop `data[0].label` of value `Label one` supplied to `Dropdown`, expected one of [null, null].

I suspect this is just a problem with the prop type definitions?

**Comment by n4kz** [comment]
Thanks for reporting! Released fix in `0.5.1`.
