### ISSUE TITLE
After focus textinput User have to tap twice to select any value in dropdown.

### ISSUE THREAD

**Issue by Pavaneshpratap** [n4kz/react-native-material-dropdown#264]

**Comment by felops** [comment]
If you are starting a new project I recommend you to not use this library, because it's not being maintained. But if you already have this library on your project, I recommend to replace by this one: https://www.npmjs.com/package/react-native-material-dropdown-v2-fixed

**Comment by Pavaneshpratap** [comment]
> If you are starting a new project I recommend you to not use this library, because it's not being maintained. But if you already have this library on your project, I recommend to replace by this one: https://www.npmjs.com/package/react-native-material-dropdown-v2-fixed

getting same issue in this library also

**Comment by Pavaneshpratap** [comment]
I got the solution for this bug..
just add keyboardShouldPersistTaps="always" in flatlist in this library..
path in library where we will change : src/components/dropdown/index.js
so therefore i'm closing this issue.
thank you
