### ISSUE TITLE
null is not an object (evaluating 't.scroll.scrollTo')

### ISSUE THREAD

**Issue by kiwidood** [n4kz/react-native-material-dropdown#28]
This crash can be reproduced by rapidly clicking a dropdown menu. Using RN: 0.45.1, react-native-material-dropdown 0.5.0.

The issue can be fixed by adding an additional condition to the if statement on line: 241 of src/components/dropdown/index.js so the setTimeout so it looks like this:
`if (this.mounted && this.scroll !== null) {`

**Comment by n4kz** [comment]
Thanks for reporting! Fixed and released in `0.5.2`.
