### ISSUE TITLE
TypeError: Cannot read property 'Dropdown' of undefined

### ISSUE THREAD

**Issue by MyAndroidNetZWJ** [n4kz/react-native-material-dropdown#281]
When I'm done with the download command npm install --save react-native-material-dropdown,
Compile the code based on the demo instance. After the code is run, an error is reported when you click the code.
TypeError: Cannot read property'Dropdown' of undefined

How can I solve this problem? Has anyone come across this?

**Comment by konikjoshi3** [comment]
Getting same problem after upgrading react native version to 0.75 is any one find any solution for this?

**Comment by gkasireddy202** [comment]
@konikjoshi3, @MyAndroidNetZWJ  - How can we resolve the issue below in 0.78? Any idea?

Getting the below error in RN@0.78.0

TypeError : Cannot read property 'style' of undefined , js engine:hermes.

<img width="423" alt="Image" src="https://github.com/user-attachments/assets/f2834657-1097-4ab7-88af-0026365b32cb" />
