### ISSUE TITLE
SyntaxError: Missing class properties transform

### ISSUE THREAD

**Issue by bohrend** [n4kz/react-native-material-dropdown#29]
Hi I am having trouble adding this lib to my project, could someone please assist 

> react-native-cli: 2.0.1
> react-native: 0.49.3

![screenshot](https://user-images.githubusercontent.com/9966431/31705737-dab849d6-b3e6-11e7-87e6-fca7ce166740.jpg)

`import {Dropdown} from 'react-native-material-dropdown';`

...
`   <Dropdown
                    label={Strings.COMMISSION_HEADING}
                    data={channelOptions}/>`
...

**Comment by n4kz** [comment]
Thanks for reporting and sorry for delayed reply. Looks like this relates to misconfigured babel and can not be fixed from this component directly.
