### ISSUE TITLE
remove bottom border

### ISSUE THREAD

**Issue by mistryhiren94** [n4kz/react-native-material-dropdown#30]
how to remove bottom border of picker, i am applying in pickerStyle but it won't reflacting
please help
thank you

**Comment by n4kz** [comment]
Thanks for question. Border can be removed from `TextField` component starting from 0.10.0, as described in n4kz/react-native-material-textfield#47. You have to pass `inputContainerStyle={{ borderBottomColor: 'transparent' }}` to `Dropdown` component.

**Comment by omerts** [comment]
You could also use ```inputContainerStyle={{ borderBottomWidth: 0 }}```, to not render it, instead of rendering a transparent one.

**Comment by amirbhz86** [comment]
you sould give this code too
baseColor={'white'}
