### ISSUE TITLE
Sample is too hard to understand

### ISSUE THREAD

**Issue by milon87** [n4kz/react-native-material-dropdown#31]
Thanks for your effort.  
I am new in RN or JS. How can I get selected item/index from Dropdown?
any simple example?

Thanks

**Comment by milon87** [comment]
What I like to do, 

<Dropdown
                    label='Service Type'
                    data={data}
                    dropdownPosition={0}
                    itemCount={5}
                    onSelectedItem={change the state so otehr can get the change}
                    containerStyle={{paddingLeft: 16, paddingRight: 16}}
                />

how to achieve that?

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. To call component methods you have to obtain a reference to component using a `ref` prop. Usually this can be done by using the following pattern:

```javascript
/* In render() method */
<Dropdown ref={(ref) => this.dropdown = ref} />

/* In some event handler */
if (this.dropdown) {
  /* Get selected value */
  this.dropdown.value()

  /* Get selected index */
  this.dropdown.selectedIndex()

  /* Get selected item (as passed to data */
  this.dropdown.selectedItem()
}
```

In example project closure is replaced with a method bound to `this`, to get small performance gain.

However if you need to execute some code in response to value updates take look at `onChangeText` prop:

```javascript
/* In constructor() */
this.onChange = this.onChange.bind(this)

/* In render() method */
<Dropdown onChangeText={this.onChange} />

/* onChange event handler */
onChange(value, index, data) {
  /* handle event */
}
```

**Comment by harshvitra** [comment]
Please add this to Read ME, really very important
