### ISSUE TITLE
how to add nice border around the dropdown?

### ISSUE THREAD

**Issue by dewabagasql** [n4kz/react-native-material-dropdown#32]
i tried add a border in container style, but it doesn't looks good. maybe u can help me

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Border for dropdown view can be added using `pickerStyle` prop, and for base component - using `containerStyle` as you have tried. To improve visual appearance of styled `TextField` I would suggest to add some padding with `containerStyle`, adjust `labelHeight` and `labelPadding` as described in n4kz/react-native-material-textfield#30.
