### ISSUE TITLE
labelFontSize has no effect

### ISSUE THREAD

**Issue by v3yr0n** [n4kz/react-native-material-dropdown#37]
Hey!
Thanks for this good work, very useful :)
Just wanted to tell you that there is an error on the README. You have labelFontSize but that property does not exist (or at least I was not able to find it) I think that you meant to write fontSize. 
Is that right?

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. This property is defined in underlying [`TextField`](https://github.com/n4kz/react-native-material-textfield) component referenced later in readme.

I've placed this prop in readme to make customisation easier without deep component knowledge. Probably it should be removed in future.
