### ISSUE TITLE
Label Display

### ISSUE THREAD

**Issue by chongdog83** [n4kz/react-native-material-dropdown#38]
Is there a way to keep the field label above the field?  

What I mean by this is that when there is no value set on the drop down, the label is inside the dropdown field, but when you select a value, the label then shows up above the field.

I would like it to always be above the field, because my other fields which are not dropdowns have labels above the field.
![screen shot 2017-11-09 at 11 19 16 pm](https://user-images.githubusercontent.com/813101/32642777-9b364504-c5a4-11e7-9dcb-7ccb5894aa97.png)
![screen shot 2017-11-09 at 11 19 45 pm](https://user-images.githubusercontent.com/813101/32642778-9b4949f6-c5a4-11e7-8a36-187554c80077.png)

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. You can use `defaultValue=' '` prop with a single space character to get desired behaviour.
