### ISSUE TITLE
Get a selected value in drop down list

### ISSUE THREAD

**Issue by harikanammi** [n4kz/react-native-material-dropdown#39]
I am using this module. It's all working fine. I am running a sample react-native app. In this app i am displaying 1-100 years in drop down list. My question is how to get a selected value in drop down list. 
Here is my code:
```
import { View, ScrollView, Text, TextInput, TouchableOpacity, Image, Keyboard, LayoutAnimation, Alert } from 'react-native';
import { Dropdown } from 'react-native-material-dropdown';
var data = [];
class AddPatients extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
          value: ''
             }
           }
componentWillMount() {
    for (var i = 1; i <= 100; i++) {
      data.push({ value: i.toString() });
    }
  }
  selectedYear(value, index, data) {
    this.setState({
      value: data[value]
    });
  }
render() {
    return (
  <View style={{ flex: 0.027, alignItems: 'flex-start', justifyContent: 'center' }}>
                        <Dropdown
                          label="Select Year"
                          data={data}
                          baseColor={'black'}
                          containerStyle={{ width: 130 }}
                          selectedItemColor={'black'}
                          value={this.state.value}
                          onChangeText={this.selectedYear.bind(this)}
                        />
                      </View>
)
}
        }
```

Here is my screenshot:
![screen shot 2017-11-15 at 10 56 28 am](https://user-images.githubusercontent.com/31063894/32820318-b4689420-c9f3-11e7-84f6-242790a18361.png)

**Comment by DevGayathri1992** [comment]
selectedName(value, index) {
      this.setState({
        name: `${value}`  //replace your code value: `${value}` 
      });
    }
render(){
<Dropdown
                          label="Select Year"
                          data={data}
                          baseColor={'black'}
                          containerStyle={{ width: 130 }}
                          selectedItemColor={'black'}
                          value={this.state.value}
                         onChangeText={(index, value) => this.selectedName(index, value)}
                        />
}
i think it ll work

**Comment by harikanammi** [comment]
@DevGayathri1992 Thanks for your response, It's working. Thank you.
