### ISSUE TITLE
How to use id and value together

### ISSUE THREAD

**Issue by Sunil-tc** [n4kz/react-native-material-dropdown#40]
I want to show value in select box. After selecting, I want to pass id of selected field.

I want like, 
<select>
     <option value="1">Name</option>
</select>
 
How can I do this ?

**Comment by newfylox** [comment]
Agree! I cannot fit [tcomb-form-native](https://github.com/gcanti/tcomb-form-native) library with this dropdown because their object signature is something like this
```javascript
{
  text: "my text",
  value: "my_id_number"
}
```
and then this library automatically uses `value` as output text. It would be nice to accept a custom object and choose our key and value properties, something like that:
```javascript
const data = {
  name: "My name",
  id: 2,
  email: "email@example.com"
}

<Dropdown data={data} keyAttribute={"name"} valueAttribute{"id"} />
```

**Comment by Sunil-tc** [comment]
I'm using this in redux form. It's taking "value" as default. I need to send "id".
After changing like above also, i'm facing same problem.

**Comment by kayzenkayzen** [comment]
You can use .map() to map your object.

`yourArray.map((item) => {
    return {
       value: item.id,
       label: item.name,
    };
})`

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Starting from `0.7.0` `Dropdown` received new props `valueExtractor` and `labelExtractror`. Now it's possible to pass objects with any shape in `data` array with a custom extractors set by those props.

**Comment by newfylox** [comment]
Alright, good news!

**Comment by vinothjdx** [comment]
how to use valueExtractor & labelExtractror?? is it like flatlist keyextractor

**Comment by Brianwebb22** [comment]
I would also greatly appreciate someone giving a working example of the valueExtractor & labelExtractor.

**Comment by khuznain** [comment]
If anyone got confused with valueExtractor & labelExtractror
If u have a complex object and want to show a label inside the list you can use labelExtractor it and if you want to select some value for example Id use valueExtractor

For example, we have 

```
const data = {
  name: "My name",
  id: 1,
  email: "email@example.com"
}

labelExtractor={({name}) => name}
valueExtractor={({id}) => id}

```
