### ISSUE TITLE
How to remove the bottom border in the dropdown

### ISSUE THREAD

**Issue by udayasri** [n4kz/react-native-material-dropdown#41]
Hi , 

I want to remove the bottom border of the dropdown. Is there anyway to do it ? 

Thanks in advanced.

**Comment by hosembafer** [comment]
Hello,
See first this issue https://github.com/n4kz/react-native-material-dropdown/issues/30

**Comment by udayasri** [comment]
Thanks it works.

**Comment by hosembafer** [comment]
Sure, please close issue if solved.
