### ISSUE TITLE
How to determine a default value

### ISSUE THREAD

**Issue by kyhnlbyrk** [n4kz/react-native-material-dropdown#42]
Here is my problem: The first time my component is loaded I want to make a default value of the dropdown. I.E 'date' 'campaign' 'user' is my data with a label: group by. When the component first loaded, the label is showing in dropdown  but I want to show one of my datas. How can I do this ?

**Comment by carlolucadei** [comment]
@kyhnlbyrk as default value you should use *value* attribute

<Dropdown
  value={'Default value'}
  ...
  ...
/>
