### ISSUE TITLE
Touchable Area

### ISSUE THREAD

**Issue by ershubhamgarg** [n4kz/react-native-material-dropdown#43]
@n4kz 
Is there any way to increase the touchable area of the dropdown ?

**Comment by n4kz** [comment]
Thanks for question! Just finished implementing support for [`hitSlop`](https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#hitslop) prop along with some other props implemented by `TouchableWithoutFeedback` component. Released in `0.5.0`.
