### ISSUE TITLE
Error labels like react-native-material-textifled

### ISSUE THREAD

**Issue by Noitidart** [n4kz/react-native-material-dropdown#45]
Thanks for such amazing modules! Is it possible to do error labels (with animation) as we see in react-native-material-textfield - https://github.com/n4kz/react-native-material-textfield ?

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Yes, all props unused by `Dropdown` component are passed down to it's base component (`TextField` with default `renderBase`).
