### ISSUE TITLE
Do want the selected text color be black

### ISSUE THREAD

**Issue by poc7667** [n4kz/react-native-material-dropdown#46]
Seems no way to make this color to be black and also keep the dropdown items in different colors
![inline](https://i.imgur.com/A2kgxU8.png=300x "Title")

**Comment by Biller17** [comment]
I can't seem to print the selected item, I set in value my state but it won't show any text

**Comment by gabriellim** [comment]
@poc7667 How did you set the dropdown item backgroundColor? It must be through the pickerStyle prop

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Different colors for dropdown items are definitely possible, please use `itemColor` and `selectedItemColor` props to override default values.
