### ISSUE TITLE
Drops Refs in Example

### ISSUE THREAD

**Issue by ssomnoremac** [n4kz/react-native-material-dropdown#47]
I'm not a fan of using `refs` in RN unless as a last resort as somewhat evidenced by the complexity of the example for what should be easy to accomplish.

Wouldn't it just be easier to pass the `label` or anything really to the `onChangeText` function like so:
```
<Dropdown
  ...
  data={nameData}
  onChangeText={(value, i, data) => this._onChangeText(value, i, data, 'name')}
/>
```

```
_onChangeText(value, i, data, field) {
  this.setState({[field]: data[i]._value})
}
```

**Comment by ebouJ** [comment]
I not a big fan of ref either , So I decided to use your way and it works for me.
I just made a modification to your _onChangeText function and it works like a charm 

_onChangeText(value, i, data, field) {
  this.setState({[field]: data[i].value})
}

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. `onChangeText` works the same way it does in RN `TextInput` except additional arguments passed for convenience. Using `ref` seems to be de-facto standard solution for many cases in RN world and probably we should not reinvent the wheel by replacing callbacks with some form of symbolic links.
