### ISSUE TITLE
Question for long data like 1000 rows

### ISSUE THREAD

**Issue by ckdvivedi** [n4kz/react-native-material-dropdown#48]
Taking too much time to show picker. There is any solution.

**Comment by itanhduy** [comment]
You should create a custom list for this case. Instead of using this plugin. Create a Flatlist inside modal/popup.
1000 rows can break performance your app with this plugin

**Comment by n4kz** [comment]
Thanks for question. I've refactored `Dropdown` and replaced `ScrollView` with `FlatList` so rendering should happen faster on large lists. Released in `0.8.0`.
