### ISSUE TITLE
[Feature Request] Action Overflow Menu

### ISSUE THREAD

**Issue by RishitKedia** [n4kz/react-native-material-dropdown#5]
Hey there, Alexander! 👋 

This is awesome! Thank you for all your work. 🙏 

Would love to use this for the `Action Overflow Menu` as well. Having just the dropdown menu being rendered when an external component (like an Icon/Button) is tapped, would be great. 😎 

![action-overflow-menu](https://user-images.githubusercontent.com/7033218/28482789-0c72a126-6e7b-11e7-84dc-423e9c5e477b.png)

Reference: [https://material.io/guidelines/components/menus.html](https://material.io/guidelines/components/menus.html)

Let me know what you think about this. Thanks! 💪

**Comment by n4kz** [comment]
Thanks for your feedback! This will require some code refactoring, but is definitely possible. Will try to make dropdown component more abstract and untie it from text field.

**Comment by 4ship** [comment]
Any updates?

**Comment by 4ship** [comment]
This is could help : https://github.com/instea/react-native-popup-menu

**Comment by n4kz** [comment]
Almost finished with refactoring in last release. Will add docs and examples in the next one.

**Comment by n4kz** [comment]
Done with refactoring. Now it's possible to configure dropdown behaviour (#14) and attach it to arbitrary base component. Resulting code is not very clean, but I hope I can improve it in next releases.

```javascript
<Dropdown data=[]
  rippleInsets={{ top: 0, bottom: 0 }}
  labelHeight={32}
  renderBase={() => /* insert component here */}
/>
```

**Comment by RishitKedia** [comment]
@n4kz This is pretty cool! 👍

I just managed to get this working after tweaking a few `props` and `styles`. 😎

Would also love to have the `rippleCentered` and `rippleContainerBorderRadius` props to control the `ripple` because my base component is just an icon. 😛

Thank you, Alexander! 🙏

**Comment by RishitKedia** [comment]
Hey, @juanmanuelarze! 👋 

Sure, here's an example: 

```javascript
import { Dropdown } from 'react-native-material-dropdown';
import { MaterialIcons } from '@expo/vector-icons';

const data = [
  { value: 'Upgrade' },
  { value: 'Settings' },
  { value: 'About' },
  { value: 'Sign out' }
];

<Dropdown
  data={data}
  renderBase={() => (
    <MaterialIcons
      name="more-vert"
      color="#fff"
      size={24}
      style={{
        paddingTop: 8;
        paddingBottom: 8;
        paddingLeft: 8;
        paddingRight: 8;
      }}
    />
  )}

  rippleInsets={{ top: 0, bottom: 0, left: 0, right: 0 }}
  containerStyle={{ width: 40, height: 40 }}

  dropdownPosition={1}
  itemColor="rgba(0, 0, 0, .87)"
  pickerStyle={{
    width: 128,

    left: null,
    right: 0,

    marginRight: 8,
    marginTop: 24
  }}
/>
```

You can customize these `props` and `styles` according to your needs. 👨‍💻 

Hope that helps! 😃

**Comment by juanmanuelarze** [comment]
@RishitKedia yeah man thath is what i needed, thanks a lot
