### ISSUE TITLE
Disable the dropdown

### ISSUE THREAD

**Issue by HugaertsDries** [n4kz/react-native-material-dropdown#50]
Is it in any way possible to disable the use of the dropdown?
I already tried with the Text Input prop "editable= {false}" with no affect.
Thanks in advance!

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Please use `disabled={true}` prop.

**Comment by BrianKaizuntus** [comment]
df

**Comment by springer12** [comment]
Thank you!!!

**Comment by CVRamana** [comment]
> Thanks for question and sorry for delayed reply. Please use `disabled={true}` prop.

hey it is working fine, but now start showing the bottomBorder after disabling, I have seen and tried  the solution for removing the borderBottom but doesnt.
