### ISSUE TITLE
Different textAlign on iOs & Android

### ISSUE THREAD

**Issue by hcandia-lagash** [n4kz/react-native-material-dropdown#51]
On iOs the text of the item is set left to right and if the text is longer than component width it makes the text truncate (ellipsis), instead of android, on android the text is set right to left and don't truncate the text.

Android
![image](https://user-images.githubusercontent.com/8668781/34391105-a996f29e-eb22-11e7-94c2-f54f43607829.png)

iOs
![image](https://user-images.githubusercontent.com/8668781/34391910-750b98c2-eb27-11e7-94d9-16f004ee698a.png)

I have the same code to both platforms

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. This looks like a bug in RN `TextInput` described in  facebook/react-native#14845. Sadly all issues that I've found are closed but not fixed. I've experimented a bit and could not find any usable fix.
