### ISSUE TITLE
Are there any ways to create dropdown with no text in TextField?

### ISSUE THREAD

**Issue by Stalder** [n4kz/react-native-material-dropdown#52]
I'm trying to create a dropdown menu, which drops when you press icon on the toolbar. But i can't find a legal way to don't render text in TextField, or set it empty after selection. Is it possible without editing lib source files?
P.S. Sorry for my english :(

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Please take a look at issue #5 for code sample and discussion.
