### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by ayercm** [n4kz/react-native-material-dropdown#54]
I found two issues, one of which I was able to fix with reference to https://github.com/facebook/react-native/issues/14935 (the location of a critical script has changed from the packager folder to the scripts folder).

The second issue is beyond me. I get a successful build,

> ** BUILD SUCCEEDED **
> 
> Installing build/Build/Products/Debug-iphonesimulator/example.app
> Launching org.reactjs.native.example.example

and the packager is running OK, but I get this error in the simulator when launching the app,

> Failed to load bundle... index.ios.bundle

because of an

> Invalid or unexpected token (While processing preset: ".../example/node_modules/babel-preset-react-native/index.js")

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Looks like all those issues are related to your local setup and babel configuration. Please, try running example project in clean environment.
