### ISSUE TITLE
Dropdown Data

### ISSUE THREAD

**Issue by dwivediamit** [n4kz/react-native-material-dropdown#56]
My dropdown data is coming from api how to render in dropdown data field please help........
                  label=''
                  value="Pure Austin Fitness"
                  data={location_list.name}
                  baseColor="#fff"
                  textColor="#fff"
                  itemColor="#000"
                  selectedItemColor="#000"
                  fontSize={18}
                  dropdownPosition={0}
I want to render location_list name in data field

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Starting from `0.7.0` you can use `valueExtractor` prop for `data` array with custom item shape.

```javascript
<Dropdown
  label=''
  data={location_list}
  valueExtractor={({ name }) => name}
/>
```

**Comment by dwivediamit** [comment]
Thank you for your reply, I will check this.
