### ISSUE TITLE
How to use method value()

### ISSUE THREAD

**Issue by Donhv** [n4kz/react-native-material-dropdown#59]
I don't understand how to use method value(). 
ex: I want show <text>..</text> = item select by method value()
Help me!

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. `value()` method was added for consistency with `TextInput` and allows to get a string value from underlying `TextInput` component. In general case `selectedIndex()` and `selectedItem()` methods can be more usable. Those methods can be called on a ref to `Dropdown` component. For more details on using refs please take a look at [example](https://github.com/n4kz/react-native-material-dropdown/blob/master/example/app.js).
