### ISSUE TITLE
Label font color

### ISSUE THREAD

**Issue by semiautomatix** [n4kz/react-native-material-dropdown#6]
Any chance we could have this property added?

**Comment by n4kz** [comment]
Do you need to change label color alone, without affecting accessory and underline? If yes, there is `baseColor` prop for that.

**Comment by semiautomatix** [comment]
Thanks for the reply! 

`baseColor` does seem to change the underline and continues to give the field an appearance of "highlighted" even when not in focus.

**Comment by n4kz** [comment]
Sorry for logical mistake in my previous answer. `baseColor` affects accessory, underline, ripple and label in inactive state. Active state uses `tintColor` for label and underline, but is not visible under dropdown and is useless in current dropdown implementation.

**Comment by semiautomatix** [comment]
Ok, thanks for the answer though.

**Comment by stevula** [comment]
So is there no plan to support setting label color?

**Comment by ProfessionalAmateur** [comment]
@n4kz: Are you saying the `tintColor` should change the label text after a dropdown row has been selected?  I have set the `baseColor` for the label when I first render the component and nothing has been select, but I would like to be able to change the label color after a row is selected and the label animates to above the `TextField` is this possible?  Thank you
