### ISSUE TITLE
Dropdown not displaying on iOS device

### ISSUE THREAD

**Issue by stanly-johnson** [n4kz/react-native-material-dropdown#60]
The dropdown works fine on Simulator, but while testing on device the dropdown does not show or is really slow. Any solutions? What am I doing wrong?

![screen shot 2018-01-10 at 5 19 34 pm](https://user-images.githubusercontent.com/6850913/34771404-81b0c800-f62a-11e7-8b38-6acf446e6ff6.png)

**Comment by moussasarr** [comment]
I am facing the same issue. My dropdown looks stuck and is too slow to open and close . I am thinking maybe changing the property values for animationDuration, rippleOpacity and shadeOpacity would help but I am not sure. Anyway, did you find a solution ? If I cannot find a solution today I am just going to try with react-native-modal-dropdown and see if the problem persists. Anyway let me know

**Comment by stanly-johnson** [comment]
I was not able to find a solution. I ended up using Picker in React Native. https://facebook.github.io/react-native/docs/picker.html

**Comment by moussasarr** [comment]
Oh ok . I found a solution . Basically the version I was using had a ScrollView I think to handle the list of items. They replaced it with a FlatList, which worked better for long lists of items starting version 0.8.0. So I just upgraded from 0.4 to 0.9 and it did the trick.

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. `Dropdown` should work better on large lists starting from `0.8.0` as noted by @moussasarr. Animation synchronisation and duration were also improved to provide more reliable performance.
