### ISSUE TITLE
StatusBar becomes light when dropdown open

### ISSUE THREAD

**Issue by inferusvv** [n4kz/react-native-material-dropdown#62]
I found strange issue. When I open dropdown - my status bar become light.

Status bar color implemented in next way in my root component:

```
<StatusBar backgroundColor="rgba(0,0,0,0.2)" barStyle="dark-content" translucent />
```

![08nwyrnepzy](https://user-images.githubusercontent.com/3227120/34919756-5e5983a4-f979-11e7-8499-cef755e0c8ff.jpg)
![opgzhilb4mg](https://user-images.githubusercontent.com/3227120/34919758-614ba394-f979-11e7-8349-b184c90c2ed6.jpg)

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Looks like this should be fixed in RN, however there is an alternative solution, based on fix in `styles.xml`. Please take a look at [facebook/react-native#7474](https://github.com/facebook/react-native/issues/7474#issuecomment-288814366).
