### ISSUE TITLE
Change height of dropdown

### ISSUE THREAD

**Issue by vudvhitech** [n4kz/react-native-material-dropdown#64]
Hi there,I'm Vu
Thank you for all your work 😋
I have a problem. I want to create border for Dropdown, but it is too height . I need to change height. And I changed it by add height property in containerStyle
containerStyle={{
                            height: 30,
                          }}
But it's not work. can you suggest me the way change its height?

<img width="331" alt="normal" src="https://user-images.githubusercontent.com/5957138/35202740-f20a323c-ff56-11e7-823d-d55d91c48c31.png">

<img width="323" alt="issue" src="https://user-images.githubusercontent.com/5957138/35202739-f1ae9576-ff56-11e7-81e7-d74db9e07915.png">

**Comment by n4kz** [comment]
Thanks for question. Free space amount can be controlled with `labelHeight` and `labelPadding`. For more details please take look at n4kz/react-native-material-textfield#30.

**Comment by vudvhitech** [comment]
many thanks. it's works 🎉
