### ISSUE TITLE
Dropdown takes time to close

### ISSUE THREAD

**Issue by swatkholiya** [n4kz/react-native-material-dropdown#67]
After selecting item from menu i see that dropdown takes time to close . Has anyone faced this ?

**Comment by kodie** [comment]
I'm experiencing this as well. There's also a delay when opening the dropdown as well.

**Comment by slorber** [comment]
for the initial delay it's because we want the ripple effect to be visible.

I've made a PR to have better control on that delay and also ability to disable the ripple effect: https://github.com/n4kz/react-native-material-dropdown/pull/71

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Starting from release `0.10.0` dropdown should close faster than before.
