### ISSUE TITLE
The start position of dropdown looks weird if the last item is currently selected (if dropdownPosition is set)

### ISSUE THREAD

**Issue by longsangstan** [n4kz/react-native-material-dropdown#69]
![img_1983](https://user-images.githubusercontent.com/16218020/35963326-5672713a-0cef-11e8-9d26-09f24c33c533.PNG)

In the image above, "angle" is the last item of a lengthy list of 2x items.

I believe the problem is due to the `scrollTo`  method of `<ScrollView>` in line 301 in `dropdown/index.js`.

I think to fix this we have to calculate the correct offset of the last few items? I haven't tried it yet.

Great library btw!

**Comment by kodie** [comment]
@longsangstan Can you try installing my fork and see if you still have this issue? `npm install github:kodie/react-native-material-dropdown#master`

**Comment by n4kz** [comment]
Thanks for issue! Released fix in `0.10.0`. Overscroll is now disabled for positive and negative `dropdownPosition`.
