### ISSUE TITLE
Invalid attempt to destructure non-iterable sequence 

### ISSUE THREAD

**Issue by vphong** [n4kz/react-native-material-dropdown#72]
Hey, just trying to test out the example from the readme. I get this error with just:

```js
class Example extends Component {
  render() {

    let data = [{
      value: 'Banana',
    }, {
      value: 'Mango',
    }, {
      value: 'Pear',
    }];

    return <Dropdown label="Favorite fruit" data={data}/>
}
```
I'm on `"react": "16.2.0"`, `"react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz"`, and `"expo": "^25.0.0"`. Could this be Expo's fault?

**Comment by n4kz** [comment]
Thanks for question. Probably this issue is related to babel configuration. Please, try running example project without expo in clean environment.
