### ISSUE TITLE
style for label

### ISSUE THREAD

**Issue by ProMasoud** [n4kz/react-native-material-dropdown#75]
Hi, thanks for great works

I find out plugin have a missing style for label 
I want to change label font but no way to do this

**Comment by n4kz** [comment]
Thanks for question! Please use `labelTextStyle` prop for label styling. This prop comes from underlying [`TextField`](https://github.com/n4kz/react-native-material-textfield) component and is documented there.

**Comment by wzup** [comment]
@n4kz 

Doesn't work. Neither `margin`, nor `padding` can be applied!
```javascript
labelTextStyle: { marginBottom: 100 } // doesn't work
``` 

I need to change `basePadding` prop of `Label`. How can I do it?

![screen shot 2018-06-23 at 7 11 05 pm](https://user-images.githubusercontent.com/3880497/41811497-7c7c2cba-7719-11e8-974f-86bb3d1f4340.png)

**Comment by lalosh** [comment]
@n4kz Thank you for your great component! =D 
but I am sorry `labelTextStyle` didn't work.. I wanted to make the label textAlign to 'right'

**Comment by Saqib92** [comment]
Still not working.
