### ISSUE TITLE
How can I change the font family?

### ISSUE THREAD

**Issue by AgNm** [n4kz/react-native-material-dropdown#78]
1. How can I change the font family of Label & dropdown values?

I have applied the font family but it is only applying to the value which I have selected.

```
                   <Dropdown
                                labelFontSize='12'
                                 style={{fontSize : 14, fontFamily: Fonts.TitilliumWeb}}
                                data={data}
                              />
```

2. Also how can I increase the width & height of the dropdown?

**Comment by pdsouza** [comment]
`itemTextStyle` prop can be used for dropdown items, see: https://github.com/n4kz/react-native-material-dropdown/issues/18

**Comment by AgNm** [comment]
Can you please share some example code? @pdsouza

**Comment by pdsouza** [comment]
@AgNm To change the `fontFamily` and `fontSize` for the dropdown items this works for me:

```
<Dropdown
    itemTextStyle={{fontFamily:  'Avenir-Light'}}
    fontSize={12}
/>
```

**Comment by n4kz** [comment]
Thanks for questions!

1. Could not reply better than @pdsouza just did. Thanks!
2. Dropdown height depends on `fontSize` and `itemCount` and `itemPadding`. Dropdown width can be adjusted using `dropdownMargins`.

**Comment by AgNm** [comment]
@pdsouza @n4kz I am able to change the font family of Dropdown list using `itemTextStyle` but once I select any value, selected value has default font family, how can I change it?

**Comment by isaachinman** [comment]
Same question as @AgNm, there does not seem to be an equivalent `labelTextStyle` prop. How do we achieve this?

**Comment by piersolenski** [comment]
+1

**Comment by sajithnwijerathne** [comment]
The same issue as @AgNm  and @isaachinman, There is no any prop to change selected items, font family.

**Comment by Fallup** [comment]
@n4kz This shouldbe re-opened as there is now way how you can set the `fontFamily` for the label. Adding a `labelTextStyle` would be great.

**Edit:**
Just found the https://github.com/n4kz/react-native-material-dropdown/issues/75#issuecomment-367276318 which actually worked even thought it is missing in TS type definitions.
