### ISSUE TITLE
Missing RCTAnimation and libRCTAnimation

### ISSUE THREAD

**Issue by brianmclachlin** [n4kz/react-native-material-dropdown#8]
Wasn't working in ios, had to bring in the RCTAnimation library from react-native and libRCTAnimation.a. Not sure if this is the same for everyone else. If so, might be worth noting in the read me.

**Comment by n4kz** [comment]
In recent RN versions RCTAnimation is linked by default, so this should not cause any troubles.

**Comment by brianmclachlin** [comment]
Must be because I am running 0.36. Thanks.
