### ISSUE TITLE
Feature Request: Make label prop optional

### ISSUE THREAD

**Issue by kodie** [n4kz/react-native-material-dropdown#80]
Currently `label` prop is required when I really don't think it should be. It was mentioned in #16 to make it optional and the issue was closed however `label` is still required.

In order to completely remove the label I have to do something like this:

```
<Dropdown
  label=''
  labelHeight={ 0 }
  inputContainerStyle={{ marginBottom: -10 }}
/>
```

**Comment by n4kz** [comment]
Thanks for request. Starting from `0.11.0` empty label is added in `renderBase()` automatically and is not required anymore by `Dropdown`.

**Comment by wzup** [comment]
@n4kz 
 
I use `0.11.1` and I get warning that `label` is required!

How to style label? I need to raise it a bit higher over the select
