### ISSUE TITLE
Question: using Fetch to supply Data

### ISSUE THREAD

**Issue by gauravojha** [n4kz/react-native-material-dropdown#87]
Hi,

I am trying to provide data to Dropdown using an aysnc Fetch call. I wanted to know if that was possible. 

So far, was I have been doing is:

```
function getEndpointsFromApiAsync() {
    return fetch('https://<url>myJson.json')
        .then((response) => response.json())
        .then((responseJson) => {
            return responseJson.value;
        })
        .catch((error) => {
            console.error(error);
        });
}
```

and from inside the constructor of the class calling 
``` this.data = getEndpointsFromApiAsync();```

then passing 
```
<Dropdown
                        data={this.data}
                        label='Source'
                        labelExtractor={({name}) => name}
                        valueExtractor={(value) => value}
                        onChangeText={(value) => {this.handleChange('source', value)}}
/>
```

But everytime it just throws me back an error. What is confusing for me is that if instead of using the Fetch request, if I load the same json, from my machine using import, it all works, the only change I do is
```
this.data = myJson.value;
```

The console logs in both cases show exactly the same data being returned. 

Can someone help?

**Comment by n4kz** [comment]
Thanks for question. `fetch()` returns a `Promise`, so you should not put it directly into component props, but get value from it when it will be resolved and render component with this value. However when you are loading json from a local machine, you get data directly without `Promise` wrapper.
