### ISSUE TITLE
includeFontPadding is not a valid style property

### ISSUE THREAD

**Issue by brianmclachlin** [n4kz/react-native-material-dropdown#9]
`includeFontPadding` does not work in older versions of react-native. I am running 0.36 and I think `includeFontPadding` is included in 0.40. I tried to upgrade react-native, but ran into a world of hurt. Would you be able to put a fix up for this? 

This style is in the `react-native-material-buttons` package.

![screenshot_20170803-092418](https://user-images.githubusercontent.com/13853211/28970390-5f7f5b22-78f6-11e7-8d39-60134b93aced.png)

**Comment by n4kz** [comment]
Thanks for reporting, released fix in `react-native-material-buttons` `0.4.1`, dropdown should use it if available.
