### ISSUE TITLE
is it possible to get an array of json to displaying it on dropdown list?

### ISSUE THREAD

**Issue by zxccvvv** [n4kz/react-native-material-dropdown#93]
I've an example json using state like this:
```
this.state = {"diagnosis": {
        "type": [
          "Oncology",
          "Hip And Knee"
        ],
        "kode": [
          "123",
          "321",
          "3232",
          "1231"
        ],
        "PrimaryCat": [
          "contoh1",
          "contoh2",
          "contoh3"
        ]}
}

render() {
    return (
      <View>
        <Dropdown
          label="testing"
          data={this.state.diagnosis.type}
        />
        <Dropdown
          label="kode"
          data={this.state.diagnosis.kode}
        />
      </View>
    );
  }
```

the result of dropdown is not showing the array text,

here's the example screen :

![image](https://user-images.githubusercontent.com/19633881/37578354-d41c9072-2b6a-11e8-9c0c-a7531d414a06.png)

am i wrong?

**Comment by danisbubblesdad** [comment]
The object format is [{value: [insert string you want to show in dropdown here]},...]. This tool will not work out of the box with the format that you've specified.

So in your example, you would need to map the JSON to [{value: "Oncology"},{value: "Hip And Knee"}].
